import image1 from "../abgp/abgimages/JourneyFlow1.jpg"
import image2 from "../abgp/abgimages/JourneyFlow2.jpg"
import image3 from "../abgp/abgimages/JourneyFlow3.jpg"
import image4 from "../abgp/abgimages/JourneyFlow4.jpg"
import image5 from "../abgp/abgimages/JourneyFlow5.jpg"
import image6 from "../abgp/abgimages/JourneyFlow6.jpg"
import image7 from "../abgp/abgimages/JourneyFlow7.jpg"
import image8 from "../abgp/abgimages/JourneyFlow8.jpg"
import image9 from "../abgp/abgimages/JourneyFlow9.jpg"
import image10 from "../abgp/abgimages/JourneyFlow10.jpg"
import image11 from "../abgp/abgimages/JourneyFlow11.jpg"
import image12 from "../abgp/abgimages/JourneyFlow12.jpg"
import image13 from "../abgp/abgimages/JourneyFlow13.jpg"
import image14 from "../abgp/abgimages/JourneyFlow14.jpg"
import image15 from "../abgp/abgimages/JourneyFlow15.jpg"
import image16 from "../abgp/abgimages/JourneyFlow16.jpg"
import image17 from "../abgp/abgimages/JourneyFlow17.jpg"
import image18 from "../abgp/abgimages/JourneyFlow18.jpg"
import image19 from "../abgp/abgimages/JourneyFlow19.jpg"
import image20 from "../abgp/abgimages/JourneyFlow20.jpg"
import image21 from "../abgp/abgimages/JourneyFlow21.jpg"


export {image1,image2, image3, image4,image5,image6,image7,image8,image9,image10,image11,image12,image13,image14,image15,image16,image17,image18,image19,image20,image21}